### ISSUE TITLE
How to provide a named volume

### ISSUE THREAD

**Issue by Jared-Dev** [ainoya/docker-sixpack#7]
I'm trying to figure out how to provide a named volume to the image?

I currently use the docker image as part of our `docker-compose` setup. After a restart, the data is reset (as expected with the current config). 

Here is the section of my `docker-compose` that sets up sixpack.
```yml
  sixpack:
    image: 'ainoya/sixpack'
    restart: always
    container_name: 'gs-sixpack'
    depends_on:
      - redis
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      SIXPACK_CONFIG_ENABLED: 1
      SIXPACK_CONFIG_REDIS_PORT: 6379
      SIXPACK_CONFIG_REDIS_HOST: 'gs-redis'
      SIXPACK_CONFIG_REDIS_PREFIX: 'sp_'
```
...just in case it is needed. Here is the `redis` config
```yml
  redis:
    image: 'redis:latest'
    container_name: 'gs-redis'
    restart: always
    volumes:
      - "redis_data:/data"
    ports:
     - "6379:6379"
```

BTW, thanks for the great image!
